### ISSUE TITLE
Make crawler configurable

### ISSUE THREAD

**Issue by nidhimundra** [nidhimundra/Breaking-Bots#9]
https://doc.scrapy.org/en/latest/topics/request-response.html

**Comment by vrt1shjwlkr** [comment]
I think we have the basic crawler!! But few comments about **configurability** of it:

We need to have a crawler that is configurable in terms of the following parameters: 
1. **The user_agent field** e.g. firefox, chrome, opera or any other web-browser. This is what Phillipa has mentioned in her part of the proposal.
2. **IP with which the crawler crawls web-pages should be configurable**. This is one of the _tricks_ that smart crawlers use to avoid detection. I think, the fancy way to say this thing is to use VPN for crawlers while accessing webpages.
3. Once crawling starts, the **crawling speed/aggressiveness** should be configurable; the time difference in accessing two successive pages should change statically/dynamically
4. Currently, the start of crawl is **one** entry point. We need to have **configurable multiple entry points** and **configurable crawling depth** (I think we discussed the concept of depth)

**Comment by vrt1shjwlkr** [comment]
One more thing - we need responses of all the webpages not just the _good_ ones. Because, we will be comparing the bad responses against the responses we get by accessing those pages using **Selenium**.

**Comment by nidhimundra** [comment]
https://github.com/nidhimundra/Breaking-Bots/pull/10

**Comment by nidhimundra** [comment]
https://doc.scrapy.org/en/latest/topics/request-response.html
